version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    command: --check-caps false
    restart: always
    ports: 
      - 1972
      - ${IRIS_PORT}:52773
      - 53773
    volumes:
#      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
#      - ./src/csp:/usr/irissys/mgr/csp/irisapp
